// 全局加载效果
export const LOADING_SHOW = 'BC/LOADING_SHOW';
export const LOADING_HIDE = 'BC/LOADING_HIDE';

export const FETCH_START = 'BC/FETCH_START';
export const FETCH_END = 'BC/FETCH_END';
export const FETCH_ERROR = 'BC/FETCH_ERROR';
export const FETCH_CANCEL = 'BC/FETCH_CANCEL';

// 设置网络状态
export const SET_NETWORK_INFO = 'BC/SET_NETWORK_INFO';

// 登录页 - 验证服务器
export const VALIDATE_SERVER = 'BC/VALIDATE_SERVER';
export const VALIDATE_SERVER_SUCCESS = 'BC/VALIDATE_SERVER_SUCCESS';
export const VALIDATE_SERVER_FAILURE = 'BC/VALIDATE_SERVER_FAILURE';
// 登录页 - 获取登录页配置
export const REQUEST_LOGIN_CONFIG = 'BC/REQUEST_LOGIN_CONFIG';
export const RECEIVE_LOGIN_CONFIG = 'BC/RECEIVE_LOGIN_CONFIG';
// 登录页 - 登录
export const REQUEST_LOGIN = 'BC/REQUEST_LOGIN';
export const REQUEST_LOGIN_SUCCESS = 'BC/REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILURE = 'BC/REQUEST_LOGIN_FAILURE';
export const RESET_LOGIN_STATUS = 'BC/RESET_LOGIN_STATUS';
// 登录页 - VPN配置
export const VPN_LOGIN = 'BC/VPN_LOGIN';
export const VPN_LOGIN_SUCCESS = 'BC/VPN_LOGIN_SUCCESS';
export const VPN_LOGIN_FAILURE = 'BC/VPN_LOGIN_FAILURE';
export const VPN_LOGOUT = 'BC/VPN_LOGOUT';
export const VPN_LOGOUT_SUCCESS = 'BC/VPN_LOGOUT_SUCCESS';
export const VPN_LOGOUT_FAILURE = 'BC/VPN_LOGOUT_FAILURE';
export const VPN_RELOGIN_FAILURE = 'BC/VPN_RELOGIN_FAILURE';

// 报销
export const FETCH_REIMB_TABS = 'BC/FETCH_REIMB_TABS';
export const FETCH_REIMB_TABS_LOADING = 'BC/FETCH_REIMB_TABS_LOADING';
export const FETCH_REIMB_TABS_SUCCESS = 'BC/FETCH_REIMB_TABS_SUCCESS';
export const FETCH_REIMB_TABS_FAILURE = 'BC/FETCH_REIMB_TABS_FAILURE';

export const FETCH_REIMB_LIST_TEMPLATE = 'BC/FETCH_REIMB_LIST_TEMPLATE';
export const FETCH_REIMB_LIST_TEMPLATE_LOADING = 'BC/FETCH_REIMB_LIST_TEMPLATE_LOADING';
export const FETCH_REIMB_LIST_TEMPLATE_SUCCESS = 'BC/FETCH_REIMB_LIST_TEMPLATE_SUCCESS';
export const FETCH_REIMB_LIST_TEMPLATE_FAILURE = 'BC/FETCH_REIMB_LIST_TEMPLATE_FAILURE';

export const FETCH_REIMB_LIST_DATA = 'BC/FETCH_REIMB_LIST_DATA';
export const FETCH_REIMB_LIST_DATA_LOADING = 'BC/FETCH_REIMB_LIST_DATA_LOADING';
export const FETCH_REIMB_LIST_DATA_SUCCESS = 'BC/FETCH_REIMB_LIST_DATA_SUCCESS';
export const FETCH_REIMB_LIST_DATA_FAILURE = 'BC/FETCH_REIMB_LIST_DATA_FAILURE';

export const FETCH_REIMB_LIST = 'BC/FETCH_REIMB_LIST';
export const FETCH_REIMB_LIST_LOADING = 'BC/FETCH_REIMB_LIST_LOADING';
export const FETCH_REIMB_LIST_SUCCESS = 'BC/FETCH_REIMB_LIST_SUCCESS';
export const FETCH_REIMB_LIST_FAILURE = 'BC/FETCH_REIMB_LIST_FAILURE';
export const DELETE_REIMB_LIST_ITEM = 'BC/DELETE_REIMB_LIST_ITEM';

export const RESET_REIMB_DETAIL = 'BC/RESET_REIMB_DETAIL';
export const FETCH_REIMB_DETAIL_DATA = 'BC/FETCH_REIMB_DETAIL_DATA';
export const FETCH_REIMB_DETAIL_DATA_SUCCESS = 'BC/FETCH_REIMB_DETAIL_DATA_SUCCESS';
export const FETCH_REIMB_DETAIL_DATA_FAILURE = 'BC/FETCH_REIMB_DETAIL_DATA_FAILURE';
export const MARK_REIMB_DETAIL_FINISHED = 'BC/MARK_REIMB_DETAIL_FINISHED';

export const FETCH_REIMB_DETAIL_TEMPLATE = 'BC/FETCH_REIMB_DETAIL_TEMPLATE';
export const FETCH_REIMB_DETAIL_TEMPLATE_SUCCESS = 'BC/FETCH_REIMB_DETAIL_TEMPLATE_SUCCESS';
export const FETCH_REIMB_DETAIL_TEMPLATE_FAILURE = 'BC/FETCH_REIMB_DETAIL_TEMPLATE_FAILURE';

export const RESET_REIMB_EDITOR = 'BC/RESET_REIMB_EDITOR';
export const FETCH_REIMB_EDITOR_DATA = 'BC/FETCH_REIMB_EDITOR_DATA';
export const FETCH_REIMB_EDITOR_DATA_SUCCESS = 'BC/FETCH_REIMB_EDITOR_DATA_SUCCESS';
export const FETCH_REIMB_EDITOR_DATA_FAILURE = 'BC/FETCH_REIMB_EDITOR_DATA_FAILURE';

export const SAVE_REIMB_EDITOR_DATA = 'BC/SAVE_REIMB_EDITOR_DATA';
export const SAVE_REIMB_EDITOR_DATA_SUCCESS = 'BC/SAVE_REIMB_EDITOR_DATA_SUCCESS';
export const SAVE_REIMB_EDITOR_DATA_FAILURE = 'BC/SAVE_REIMB_EDITOR_DATA_FAILURE';

export const FETCH_REIMB_EDITOR_TEMPLATE = 'BC/FETCH_REIMB_EDITOR_TEMPLATE';
export const FETCH_REIMB_EDITOR_TEMPLATE_SUCCESS = 'BC/FETCH_REIMB_EDITOR_TEMPLATE_SUCCESS';
export const FETCH_REIMB_EDITOR_TEMPLATE_FAILURE = 'BC/FETCH_REIMB_EDITOR_TEMPLATE_FAILURE';

export const FETCH_REIMB_EDITOR_FORMULA = 'BC/FETCH_REIMB_EDITOR_FORMULA';
export const FETCH_REIMB_EDITOR_FORMULA_SUCCESS = 'BC/FETCH_REIMB_EDITOR_FORMULA_SUCCESS';
export const FETCH_REIMB_EDITOR_FORMULA_FAILURE = 'BC/FETCH_REIMB_EDITOR_FORMULA_FAILURE';

export const SUBMIT_EDITOR = 'BC/SUBMIT_EDITOR';
export const SUBMIT_EDITOR_SUCCESS = 'BC/SUBMIT_EDITOR_SUCCESS';
export const SUBMIT_EDITOR_FAILURE = 'BC/SUBMIT_EDITOR_FAILURE';

export const SUBMIT_EDITOR_USERS = 'BC/SUBMIT_EDITOR_USERS';
export const SUBMIT_EDITOR_USERS_SUCCESS = 'BC/SUBMIT_EDITOR_USERS_SUCCESS';
export const SUBMIT_EDITOR_USERS_FAILURE = 'BC/SUBMIT_EDITOR_USERS_FAILURE';

export const SUBMIT_REIMB = 'BC/SUBMIT_REIMB';
export const SUBMIT_REIMB_SUCCESS = 'BC/SUBMIT_REIMB_SUCCESS';
export const SUBMIT_REIMB_FAILURE = 'BC/SUBMIT_REIMB_FAILURE';

export const SUBMIT_REIMB_USERS = 'BC/SUBMIT_REIMB_USERS';
export const SUBMIT_REIMB_USERS_SUCCESS = 'BC/SUBMIT_REIMB_USERS_SUCCESS';
export const SUBMIT_REIMB_USERS_FAILURE = 'BC/SUBMIT_REIMB_USERS_FAILURE';

export const DELETE_REIMB = 'BC/DELETE_REIMB';
export const DELETE_REIMB_SUCCESS = 'BC/DELETE_REIMB_SUCCESS';
export const DELETE_REIMB_FAILURE = 'BC/DELETE_REIMB_FAILURE';

// 审批
export const FETCH_APPROVAL_TABS = 'BC/FETCH_APPROVAL_TABS';
export const FETCH_APPROVAL_TABS_LOADING = 'BC/FETCH_APPROVAL_TABS_LOADING';
export const FETCH_APPROVAL_TABS_SUCCESS = 'BC/FETCH_APPROVAL_TABS_SUCCESS';
export const FETCH_APPROVAL_TABS_FAILURE = 'BC/FETCH_APPROVAL_TABS_FAILURE';

export const FETCH_APPROVAL_LIST_LOADING = 'BC/FETCH_APPROVAL_LIST_LOADING';
export const FETCH_APPROVAL_LIST_TEMPLATE = 'BC/FETCH_APPROVAL_LIST_TEMPLATE';
export const FETCH_APPROVAL_LIST_TEMPLATE_SUCCESS = 'BC/FETCH_APPROVAL_LIST_TEMPLATE_SUCCESS';
export const FETCH_APPROVAL_LIST_DATA = 'BC/FETCH_APPROVAL_LIST_DATA';
export const FETCH_APPROVAL_LIST_DATA_SUCCESS = 'BC/FETCH_APPROVAL_LIST_DATA_SUCCESS';
export const DELETE_APPROVAL_LIST_ITEM = 'BC/DELETE_APPROVAL_LIST_ITEM';

export const DO_APPROVAL_AGREE = 'BC/DO_APPROVAL_AGREE';
export const DO_APPROVAL_AGREE_SUCCESS = 'BC/DO_APPROVAL_AGREE_SUCCESS';
export const DO_APPROVAL_AGREE_FAILURE = 'BC/DO_APPROVAL_AGREE_FAILURE';

export const DO_APPROVAL_AGREE_DATA = 'BC/DO_APPROVAL_AGREE_DATA';
export const DO_APPROVAL_AGREE_DATA_SUCCESS = 'BC/DO_APPROVAL_AGREE_DATA_SUCCESS';
export const DO_APPROVAL_AGREE_DATA_FAILURE = 'BC/DO_APPROVAL_AGREE_DATA_FAILURE';

export const DO_APPROVAL_DISAGREE = 'BC/DO_APPROVAL_DISAGREE';
export const DO_APPROVAL_DISAGREE_SUCCESS = 'BC/DO_APPROVAL_DISAGREE_SUCCESS';
export const DO_APPROVAL_DISAGREE_FAILURE = 'BC/DO_APPROVAL_DISAGREE_FAILURE';

export const DO_APPROVAL_DISAGREE_DATA = 'BC/DO_APPROVAL_DISAGREE_DATA';
export const DO_APPROVAL_DISAGREE_DATA_SUCCESS = 'BC/DO_APPROVAL_DISAGREE_DATA_SUCCESS';
export const DO_APPROVAL_DISAGREE_DATA_FAILURE = 'BC/DO_APPROVAL_DISAGREE_DATA_FAILURE';

export const RESET_APPROVAL_PROCESS = 'BC/RESET_APPROVAL_PROCESS';
export const FETCH_APPROVAL_PROCESS = 'BC/FETCH_APPROVAL_PROCESS';
export const FETCH_APPROVAL_PROCESS_SUCCESS = 'BC/FETCH_APPROVAL_PROCESS_SUCCESS';
export const FETCH_APPROVAL_PROCESS_FAILURE = 'BC/FETCH_APPROVAL_PROCESS_FAILURE';

// 消息中心
export const FETCH_MESSAGE_LIST = 'BC/FETCH_MESSAGE_LIST';
export const FETCH_MESSAGE_LIST_LOADING = 'BC/FETCH_MESSAGE_LIST_LOADING';
export const FETCH_MESSAGE_LIST_SUCCESS = 'BC/FETCH_MESSAGE_LIST_SUCCESS';
export const FETCH_MESSAGE_LIST_FAILURE = 'BC/FETCH_MESSAGE_LIST_FAILURE';

export const RESET_MESSAGE_DETAIL = 'BC/RESET_MESSAGE_DETAIL';
export const FETCH_MESSAGE_DETAIL = 'BC/FETCH_MESSAGE_DETAIL';
export const FETCH_MESSAGE_DETAIL_SUCCESS = 'BC/FETCH_MESSAGE_DETAIL_SUCCESS';
export const FETCH_MESSAGE_DETAIL_FAILURE = 'BC/FETCH_MESSAGE_DETAIL_FAILURE';

export const SET_USER_LOGIN = 'BC/SET_USER_LOGIN'; // 用户登陆，上传设备token，ios用
export const SET_USER_LOGOUT = 'BC/SET_USER_LOGOUT'; // 用户退出，ios用

// 搜索
export const FETCH_SEARCH_META = 'BC/FETCH_SEARCH_META';
export const FETCH_SEARCH_META_SUCCESS = 'BC/FETCH_SEARCH_META_SUCCESS';
export const FETCH_SEARCH_META_FAILURE = 'BC/FETCH_SEARCH_META_FAILURE';

export const RESET_SEARCH_RESULT = 'BC/RESET_SEARCH_RESULT';
export const FETCH_SEARCH_RESULT = 'BC/FETCH_SEARCH_RESULT';
export const FETCH_SEARCH_RESULT_LOADING = 'BC/FETCH_SEARCH_RESULT_LOADING';
export const FETCH_SEARCH_RESULT_SUCCESS = 'BC/FETCH_SEARCH_RESULT_SUCCESS';
export const FETCH_SEARCH_RESULT_FAILURE = 'BC/FETCH_SEARCH_RESULT_FAILURE';

// 统计查询
export const RESET_STATISTICS_LIST = 'BC/RESET_STATISTICS_LIST';

export const FETCH_STATISTICS_LIST_LOADING = 'BC/FETCH_STATISTICS_LIST_LOADING';
export const FETCH_STATISTICS_LIST_TEMPLATE = 'BC/FETCH_STATISTICS_LIST_TEMPLATE';
export const FETCH_STATISTICS_LIST_TEMPLATE_SUCCESS = 'BC/FETCH_STATISTICS_LIST_TEMPLATE_SUCCESS';
export const FETCH_STATISTICS_LIST_TEMPLATE_FAILURE = 'BC/FETCH_STATISTICS_LIST_TEMPLATE_FAILURE';

export const FETCH_STATISTICS_LIST_DATA = 'BC/FETCH_STATISTICS_LIST_DATA';
export const FETCH_STATISTICS_LIST_DATA_SUCCESS = 'BC/FETCH_STATISTICS_LIST_DATA_SUCCESS';
export const FETCH_STATISTICS_LIST_DATA_FAILURE = 'BC/FETCH_STATISTICS_LIST_DATA_FAILURE';

// 用户中心
export const FETCH_USER = 'BC/FETCH_USER';
export const FETCH_USER_SUCCESS = 'BC/FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'BC/FETCH_USER_FAILURE';
export const CHANGE_PASSWORD = 'BC/CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'BC/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'BC/CHANGE_PASSWORD_FAILURE';

// 首页基本信息
export const FETCH_FUNCTIONS = 'BC/FETCH_FUNCTIONS';
export const FETCH_FUNCTIONS_SUCCESS = 'BC/FETCH_FUNCTIONS_SUCCESS';
export const FETCH_FUNCTIONS_FAILURE = 'BC/FETCH_FUNCTIONS_FAILURE';

// 基础资料
export const FETCH_BASEDATA_DEFINE = 'BC/FETCH_BASEDATA_DEFINE';
export const FETCH_BASEDATA_DEFINE_SUCCESS = 'BC/FETCH_BASEDATA_DEFINE_SUCCESS';
export const FETCH_BASEDATA_DEFINE_FAILURE = 'BC/FETCH_BASEDATA_DEFINE_FAILURE';
export const FETCH_BASEDATA_LIST = 'BC/FETCH_BASEDATA_LIST';
export const FETCH_BASEDATA_LIST_SUCCESS = 'BC/FETCH_BASEDATA_LIST_SUCCESS';
export const FETCH_BASEDATA_LIST_FAILURE = 'BC/FETCH_BASEDATA_LIST_FAILURE';
export const FETCH_BASEDATA_LIST_MORE = 'BC/FETCH_BASEDATA_LIST_MORE';
export const FETCH_BASEDATA_LIST_MORE_SUCCESS = 'BC/FETCH_BASEDATA_LIST_MORE_SUCCESS';
export const FETCH_BASEDATA_LIST_MORE_FAILURE = 'BC/FETCH_BASEDATA_LIST_MORE_FAILURE';
export const FETCH_BASEDATA_LIST_LOADING = 'BC/FETCH_BASEDATA_LIST_LOADING';
export const CLEAR_BASEDATA = 'BC/CLEAR_BASEDATA';
export const CLEAR_BASEDATA_LIST = 'BC/CLEAR_BASEDATA_LIST';
export const SEARCH_BASEDATA_LIST = 'BC/SEARCH_BASEDATA_LIST';
export const SEARCH_BASEDATA_LIST_SUCCESS = 'BC/SEARCH_BASEDATA_LIST_SUCCESS';
export const SEARCH_BASEDATA_LIST_FAILURE = 'BC/SEARCH_BASEDATA_LIST_FAILURE';
export const SEARCH_BASEDATA_LIST_MORE = 'BC/SEARCH_BASEDATA_LIST_MORE';
export const SEARCH_BASEDATA_LIST_MORE_SUCCESS = 'BC/SEARCH_BASEDATA_LIST_MORE_SUCCESS';
export const SEARCH_BASEDATA_LIST_MORE_FAILURE = 'BC/SEARCH_BASEDATA_LIST_MORE_FAILURE';
export const CLEAR_SEARCH_BASEDATA_RESULT = 'BC/CLEAR_SEARCH_BASEDATA_RESULT';

// 工作
export const FETCH_NETLINK = 'BC/FETCH_NETLINK';
export const FETCH_NETLINK_SUCCESS = 'BC/FETCH_NETLINK_SUCCESS';
export const FETCH_NETLINK_FAILURE = 'BC/FETCH_NETLINK_FAILURE';
