/*
* 需要离线缓存的数据包括：
* 1、FETCH_USER
* 2、FETCH_FUNCTIONS
* 3、FETCH_APPROVAL_TABS // 可以忽略？
* 4、FETCH_APPROVAL_LIST_TEMPLATE // 可以忽略
* 5、FETCH_APPROVAL_LIST_DATA // 可以忽略
* 6、FETCH_REIMB_TABS
* 7、FETCH_REIMB_LIST_TEMPLATE
* 8、FETCH_REIMB_LIST_DATA
* 9、FETCH_REIMB_EDITOR_TEMPLATE
* 10、FETCH_REIMB_EDITOR_DATA
*
*/
